version: '3'
services:
  api:
    build: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    build: ./client
    environment:
    #this worked when there wer enoent in building
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx
    ports:
    - '3050:80'
  
    